mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^timetable/', include('timetable.urls')),
]

mysite/timetable/urls.py
from django.conf.urls import url
from . import views

app_name = 'timetable'

urlpatterns = [
    url(r'^(?P<day>[a-zA-Z]+)/$', views.index, name='index'),
    url(r'^create_task/$', views.create_task, name='create_task'),
]

mysite/timetable/models.py
from __future__ import unicode_literals

from django.db import models

class Day(models.Model):
    name = models.CharField(max_length = 10)
    DSA = models.BooleanField(default=False)
    DLD = models.BooleanField(default=False)
    DSGT = models.BooleanField(default=False)
    SLS = models.BooleanField(default=False)
    ODE = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Todo(models.Model):
    task = models.CharField(max_length = 50)
    last = models.CharField(max_length = 10)

    def __str__(self):
        return self.task

mysite/timetable/forms.py
from django import forms
from .models import Day, Todo


class TaskForm(forms.ModelForm):
        class Meta:
            model = Todo
            fields = ['task', 'last']

mysite/timetable/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.http import HttpResponse
from .models import Day, Todo
from .forms import TaskForm
from django.template import RequestContext
# Create your views here.
def index(request, day):
    wday = get_object_or_404(Day, name = day)
    adays = Day.objects.all()
    tasks = Todo.objects.all()
    context = {
        "wday" : wday,
        "adays" : adays,
        "tasks" : tasks,
    }
    return render(request, 'timetable/index.html', context)

def create_task(request):
    # Get the context from the request.
    context = RequestContext(request)

    # A HTTP POST?
    if request.method == 'POST':
        form = TaskForm(request.POST)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)

            # Now call the index() view.
            # The user will be shown the homepage.
            return index(request , "Monday")
        else:
            # The supplied form contained errors - just print them to the terminal.
            print form.errors
    else:
        # If the request was not a POST, display the form to enter details.
        form = TaskForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render_to_response('timetable/create_task.html', {'form': form}, context)

mysite/timetable/templates/timetable/create_task.html
<html>
<head>

  <title>Create New Task</title>

</head>
<body>
  <form role="form" action="{% url 'timetable:index' "Monday"%}" method = "post" enctype = "multipart/form-data" >
  {% csrf_token %}
  {% for field in form %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Create a Task" />

</body>
</html>

mysite/timetable/templates/timetable/index.html
<html>
<head>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css" />

    <title>Home</title>
</head>
<body class=" dashboard"
  data-admin-utc-offset="0">
  <!-- Container -->
  <div id="container-fluid">


      <!-- Header -->
      <div id="header">
          <div id="branding">

  <h1 id="site-name"><a href="#">Timetable App</a></h1>

          </div>
</div>
<br>

{% for aday in adays%}

    <a href = "{% url 'timetable:index' aday.name %}">{{ aday.name }} | </a>

{% endfor %}
<br>
<br>
<br>
<div id="content-main">



        <div class="app-auth module">
        <table>
        <caption>
             <a class="section" title = "Represents the day of which the time tables of">{{ wday.name }}</a>
        </caption>

            <tr class="model-group">
              {% if wday.DSA%}
                <th scope="row"> Data Structurs and Algorithms </a></th>
                <td><a href="#" class="#"></a></td>
              {% endif %}
            </tr>



            <tr class="model-group">
              {% if wday.DLD%}
                <th scope="row"> Digital Logic Design </a></th>
                <td><a href="#" class="#"></a></td>
              {% endif %}
            </tr>

            <tr class="model-group">
              {% if wday.DSGT%}
                <th scope="row"> Discrete Sets and Graph Theory </a></th>
              {% endif %}
            </tr>

            <tr class="model-group">
              {% if wday.SLS%}
                <th scope="row"> Science of Living Systems </a></th>
              {% endif %}
            </tr>

            <tr class="model-group">
              {% if wday.ODE%}
                <th scope="row"> Ordianry Differential Equations </a></th>
              {% endif %}
            </tr>

        </table>
        </div>
        <br>
        <br>

        <div class="app-auth module">
        <table>
        <caption>
             <a class="section">To Do</a>
             <div id="user-tools">
              <td><a href = "{% url 'timetable:create_task' %}" class="addlink">Add</a></td>
             </div>
        </caption>
        {%for ta in tasks%}
        <tr class="model-group">
            <th scope="row"> {{ ta.task}}</a></th>
            <td><a href="#" class="#">{{ ta.last}}</a></td>
        </tr>
        {% endfor %}

</div>
</body>
</html>